### ISSUE TITLE
Failing with socket timeout error

### ISSUE THREAD

**Issue by luizbgomide** [jneilliii/OctoPrint-GoogleDriveBackup#29]
It is timeouting after about 30 seconds, I don't have it setup to do it automatically, and the last time I've done it was some 15 days ago.

```log
2022-03-01 12:26:43,944 - octoprint.plugins.backup - INFO - Creating backup zip at /home/pi/.octoprint/data/backup/.octoprint-backup-20220301-122643.zip (excluded: uploads,timelapse,timelapse_tmp)...
2022-03-01 12:26:44,315 - octoprint.plugins.backup - INFO - ... done creating backup zip.
2022-03-01 12:26:44,322 - octoprint.plugins.googledrivebackup - INFO - /home/pi/.octoprint/data/backup/octoprint-backup-20220301-122643.zip created, will now attempt to upload to Google Drive
2022-03-01 12:27:16,631 - octoprint.plugin - ERROR - Error while calling plugin googledrivebackup
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/plugin/__init__.py", line 271, in call_plugin
    result = getattr(plugin, method)(*args, **kwargs)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/util/__init__.py", line 1737, in wrapper
    return f(*args, **kwargs)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_googledrivebackup/__init__.py", line 96, in on_event
    gauth.Refresh()
  File "/home/pi/oprint/lib/python3.7/site-packages/pydrive2/auth.py", line 570, in Refresh
    self.credentials.refresh(self.http)
  File "/home/pi/oprint/lib/python3.7/site-packages/oauth2client/client.py", line 545, in refresh
    self._refresh(http)
  File "/home/pi/oprint/lib/python3.7/site-packages/oauth2client/client.py", line 761, in _refresh
    self._do_refresh_request(http)
  File "/home/pi/oprint/lib/python3.7/site-packages/oauth2client/client.py", line 780, in _do_refresh_request
    body=body, headers=headers)
  File "/home/pi/oprint/lib/python3.7/site-packages/oauth2client/transport.py", line 282, in request
    connection_type=connection_type)
  File "/home/pi/oprint/lib/python3.7/site-packages/httplib2/__init__.py", line 1726, in request
    conn, authority, uri, request_uri, method, body, headers, redirections, cachekey,
  File "/home/pi/oprint/lib/python3.7/site-packages/httplib2/__init__.py", line 1441, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/home/pi/oprint/lib/python3.7/site-packages/httplib2/__init__.py", line 1363, in _conn_request
    conn.connect()
  File "/home/pi/oprint/lib/python3.7/site-packages/httplib2/__init__.py", line 1153, in connect
    sock.connect((self.host, self.port))
socket.timeout: timed out
```

**Comment by jneilliii** [comment]
Never experienced timeout issues before, so it's either an issue with your pi reaching out to the internet to talk to Google or Google's API is currently experiencing issues and not responding maybe.

**Comment by luizbgomide** [comment]
It seems to be even worse, now the Developers Console returns a 404, and it doesn't Authorize anymore (it keeps running until it times out):
![image](https://user-images.githubusercontent.com/18707781/156660074-373ed2bd-c731-4521-8d89-9066f4345780.png)
