### ISSUE TITLE
No additional authentication buttons appear after uploading JSON

### ISSUE THREAD

**Issue by ginjj** [jneilliii/OctoPrint-GoogleDriveBackup#42]
I have installed Google Drive Backup Version: 0.1.1 on OctoPi 0.18.0 (OctoPrint 1.8.6 Python 3.7.3) and when i click upload json the screen does not change to allow authentication. 

JSON is for credentials for Web App with Google Drive API using the Internal user type (Step 8) (Google Workspace Legacy)

`{"web":{"client_id":"xxxxxxxxxxxxxx-12345678901234567890.apps.googleusercontent.com",
             "project_id":"octoprint-backup-123456",
             "auth_uri":"https://accounts.google.com/o/oauth2/auth",
             "token_uri":"https://oauth2.googleapis.com/token",
             "auth_provider_x509_cert_url":"https://www.googleapis.com/oauth2/v1/certs",
             "client_secret":"XXXXX-12345678901234567890",
             "redirect_uris":["https://jneilliii.github.io/OctoPrint-GoogleDriveBackup/"]}}`

**Comment by jneilliii** [comment]
Sorry I missed this issue when first reported. There's a good chance this is an underlying issue with a system dependency. After restarting OctoPrint could you check your octoprint.log for errors on starting?

**Comment by ginjj** [comment]
I get the following:

```
2022-11-05 19:34:44,402 - octoprint.plugin.core - ERROR - Error loading plugin googledrivefiles
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/plugin/core.py", line 1274, in _import_plugin
    module = _load_module(module_name, spec)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/plugin/core.py", line 52, in _load_module
    return imp.load_module(name, f, filename, details)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/vendor/imp.py", line 238, in load_module
    return load_package(name, filename)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/vendor/imp.py", line 212, in load_package
    return _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_googledrivefiles/__init__.py", line 12, in <module>
    from treelib import Tree, Node
ModuleNotFoundError: No module named 'treelib'
```

**Comment by jneilliii** [comment]
that one's different than what I've normally seen. Try SSH to your pi and run the following command.

```
/home/pi/oprint/bin/pip install treelib
sudo service octoprint restart
```

and check to see if the log still reports the same error.

**Comment by ginjj** [comment]
I installed treelib. At the end there is a message that google-drive-files 0.1.0 requires pydrive2

```
pi@octopi:~ $ /home/pi/oprint/bin/pip install treelib
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting treelib
  Downloading https://www.piwheels.org/simple/treelib/treelib-1.6.1-py3-none-any.whl (18 kB)
Requirement already satisfied: future in ./oprint/lib/python3.7/site-packages (from treelib) (0.18.2)
Installing collected packages: treelib
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-drive-files 0.1.0 requires pydrive2, which is not installed.
Successfully installed treelib-1.6.1
```

does google-drive-backup need google-drive-files?

Google drive Backup still didn't seem to accept my json file, so I tried installing pydrive2 - but it reported errors on install:

```
[...]
copying src/cryptography/hazmat/bindings/_rust/__init__.pyi -> build/lib.linux-armv7l-cpython-37/cryptography/hazmat/bindings/_rust
      copying src/cryptography/hazmat/bindings/_rust/asn1.pyi -> build/lib.linux-armv7l-cpython-37/cryptography/hazmat/bindings/_rust
      copying src/cryptography/hazmat/bindings/_rust/ocsp.pyi -> build/lib.linux-armv7l-cpython-37/cryptography/hazmat/bindings/_rust
      copying src/cryptography/hazmat/bindings/_rust/x509.pyi -> build/lib.linux-armv7l-cpython-37/cryptography/hazmat/bindings/_rust
      running build_ext
      generating cffi module 'build/temp.linux-armv7l-cpython-37/cryptography.hazmat.bindings._openssl.c'
      creating build/temp.linux-armv7l-cpython-37
      running build_rust
      /tmp/pip-build-env-cn183lw8/overlay/lib/python3.7/site-packages/setuptools/command/build_py.py:202: SetuptoolsDeprecationWarning:     Installing 'cryptography.hazmat.bindings._rust' as data is deprecated, please list it in `packages`.
          !!


          ############################
          # Package would be ignored #
          ############################
          Python recognizes 'cryptography.hazmat.bindings._rust' as an importable package,
          but it is not listed in the `packages` configuration of setuptools.

          'cryptography.hazmat.bindings._rust' has been automatically added to the distribution only
          because it may contain data files, but this behavior is likely to change
          in future versions of setuptools (and therefore is considered deprecated).

          Please make sure that 'cryptography.hazmat.bindings._rust' is included as a package by using
          the `packages` configuration field or the proper discovery methods
          (for example by using `find_namespace_packages(...)`/`find_namespace:`
          instead of `find_packages(...)`/`find:`).

          You can read more about "package discovery" and "data files" on setuptools
          documentation page.


      !!

        check.warn(importable)

          =============================DEBUG ASSISTANCE=============================
          If you are seeing a compilation error please try the following steps to
          successfully install cryptography:
          1) Upgrade to the latest pip and try again. This will fix errors for most
             users. See: https://pip.pypa.io/en/stable/installing/#upgrading-pip
          2) Read https://cryptography.io/en/latest/installation/ for specific
             instructions for your platform.
          3) Check our frequently asked questions for more information:
             https://cryptography.io/en/latest/faq/
          4) Ensure you have a recent Rust toolchain installed:
             https://cryptography.io/en/latest/installation/#rust

          Python: 3.7.3
          platform: Linux-5.10.103-v7l+-armv7l-with-debian-10.6
          pip: n/a
          setuptools: 65.5.1
          setuptools_rust: 1.5.2
          rustc: n/a
          =============================DEBUG ASSISTANCE=============================

      error: can't find Rust compiler

      If you are using an outdated pip version, it is possible a prebuilt wheel is available for this package but pip is not able to install from it. Installing from the wheel would avoid the need for a Rust compiler.

      To update pip, run:

          pip install --upgrade pip

      and then retry package installation.

      If you did intend to build this package from source, try installing a Rust compiler from your system package manager and ensure it is on the PATH during installation. Alternatively, rustup (available at https://rustup.rs/) is the recommended way to download and update the Rust compiler toolchain.

      This package requires Rust >=1.48.0.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for cryptography
Failed to build cryptography
ERROR: Could not build wheels for cryptography, which is required to install pyproject.toml-based projects
```

and I am getting the following in the octoprint.log

```
2022-11-05 20:40:29,852 - octoprint.server.api - ERROR - Error while executing SimpleApiPlugin googledrivebackup
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/server/api/__init__.py", line 158, in pluginCommand
    response = api_plugin.on_api_command(command, data)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/util/__init__.py", line 1688, in wrapper
    return f(*args, **kwargs)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_googledrivebackup/__init__.py", line 38, in on_api_command
    from pydrive2.auth import GoogleAuth
ModuleNotFoundError: No module named 'pydrive2'
2022-11-05 20:40:30,497 - octoprint.server.api - ERROR - Error while executing SimpleApiPlugin googledrivebackup
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/server/api/__init__.py", line 158, in pluginCommand
    response = api_plugin.on_api_command(command, data)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/util/__init__.py", line 1688, in wrapper
    return f(*args, **kwargs)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_googledrivebackup/__init__.py", line 38, in on_api_command
    from pydrive2.auth import GoogleAuth
ModuleNotFoundError: No module named 'pydrive2'
```

**Comment by jneilliii** [comment]
Yep, that's what more of what I was expecting. Recent upstream dependencies are breaking. Try the following commands and let's see if that fixes it.

```
sudo apt update
sudo apt upgrade
sudo apt install libssl-dev
sudo apt install rustc
/home/pi/oprint/bin/pip install cryptography==37.0.4
/home/pi/oprint/bin/pip install pydrive2
```

If that doesn't work then we may have to go through a full rustc update with this command

```
curl https://sh.rustup.rs -sSf | sh
```

**Comment by ginjj** [comment]
Thanks, I still got an error for pydrive2:

```
          Python: 3.7.3
          platform: Linux-5.10.103-v7l+-armv7l-with-debian-10.13
          pip: n/a
          setuptools: 65.5.1
          setuptools_rust: 1.5.2
          rustc: 1.41.1
          =============================DEBUG ASSISTANCE=============================

      error: Rust 1.41.1 does not match extension requirement >=1.48.0
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for cryptography
Failed to build cryptography
ERROR: Could not build wheels for cryptography, which is required to install pyproject.toml-based projects
```

so tried the full rustc update...   Do I need to uninstall the prior version as suggested below?

```
pi@octopi:~ $ curl https://sh.rustup.rs -sSf | sh
info: downloading installer
warning: it looks like you have an existing installation of Rust at:
warning: /usr/bin
warning: rustup should not be installed alongside Rust. Please uninstall your existing Rust first.
warning: Otherwise you may have confusion unless you are careful with your PATH
warning: If you are sure that you want both rustup and your already installed Rust
warning: then please reply `y' or `yes' or set RUSTUP_INIT_SKIP_PATH_CHECK to yes
warning: or pass `-y' to ignore all ignorable checks.
error: cannot install while Rust is installed

Continue? (y/N)
```

**Comment by jneilliii** [comment]
oh yeah, you need to do `sudo apt remove rustc` prior to running the rust install script.

**Comment by ginjj** [comment]
Thanks working now - installed rust with 

`curl https://sh.rustup.rs -sSf | sh`

the installed pydrive2
