### ISSUE TITLE
Not getting authorization URL

### ISSUE THREAD

**Issue by dwvaughn** [jneilliii/OctoPrint-GoogleDriveBackup#45]
I've followed the steps as laid out and downloaded the secrets.json file but when I click upload, I get nothing, no authorization URL or anything.  The upload button spins for about half a second then nada. (version 0.1.1)

**Comment by jneilliii** [comment]
Please check your octoprint.log after restarting OctoPrint for any errors with the plugin. I suspect the install didn't complete as expected.

**Comment by dwvaughn** [comment]
jneilliii,

Thanks for the quick response.  I did what you suggested and found the following below.
`
2022-12-28 00:46:43,989 - octoprint.server.api - ERROR - Error while executing SimpleApiPlugin googledrivebackup
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/server/api/__init__.py", line 158, in pluginCommand
    response = api_plugin.on_api_command(command, data)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/util/__init__.py", line 1688, in wrapper
    return f(*args, **kwargs)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_googledrivebackup/__init__.py", line 38, in on_api_command
    from pydrive2.auth import GoogleAuth
ModuleNotFoundError: No module named 'pydrive2'
2022-12-28 00:47:02,166 - octoprint.server.api - ERROR - Error while executing SimpleApiPlugin googledrivebackup
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/server/api/__init__.py", line 158, in pluginCommand
    response = api_plugin.on_api_command(command, data)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/util/__init__.py", line 1688, in wrapper
    return f(*args, **kwargs)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_googledrivebackup/__init__.py", line 38, in on_api_command
    from pydrive2.auth import GoogleAuth
ModuleNotFoundError: No module named 'pydrive2'
2022-12-28 00:47:21,915 - octoprint.server.api - ERROR - Error while executing SimpleApiPlugin googledrivebackup
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/server/api/__init__.py", line 158, in pluginCommand
    response = api_plugin.on_api_command(command, data)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/util/__init__.py", line 1688, in wrapper
    return f(*args, **kwargs)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_googledrivebackup/__init__.py", line 38, in on_api_command
    from pydrive2.auth import GoogleAuth
ModuleNotFoundError: No module named 'pydrive2'
2022-12-28 00:48:02,078 - octoprint.server.api - ERROR - Error while executing SimpleApiPlugin googledrivebackup
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/server/api/__init__.py", line 158, in pluginCommand
    response = api_plugin.on_api_command(command, data)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/util/__init__.py", line 1688, in wrapper
    return f(*args, **kwargs)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_googledrivebackup/__init__.py", line 38, in on_api_command
    from pydrive2.auth import GoogleAuth
ModuleNotFoundError: No module named 'pydrive2'
2022-12-28 00:48:37,707 - octoprint.server.api - ERROR - Error while executing SimpleApiPlugin googledrivebackup
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/server/api/__init__.py", line 158, in pluginCommand
    response = api_plugin.on_api_command(command, data)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/util/__init__.py", line 1688, in wrapper
    return f(*args, **kwargs)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_googledrivebackup/__init__.py", line 38, in on_api_command
    from pydrive2.auth import GoogleAuth
ModuleNotFoundError: No module named 'pydrive2'
2022-12-28 00:49:18,481 - octoprint.server.api - ERROR - Error while executing SimpleApiPlugin googledrivebackup
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/server/api/__init__.py", line 158, in pluginCommand
    response = api_plugin.on_api_command(command, data)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/util/__init__.py", line 1688, in wrapper
    return f(*args, **kwargs)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_googledrivebackup/__init__.py", line 38, in on_api_command
    from pydrive2.auth import GoogleAuth
ModuleNotFoundError: No module named 'pydrive2'
2022-12-28 00:49:51,962 - octoprint.server.api - ERROR - Error while executing SimpleApiPlugin googledrivebackup
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/server/api/__init__.py", line 158, in pluginCommand
    response = api_plugin.on_api_command(command, data)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/util/__init__.py", line 1688, in wrapper
    return f(*args, **kwargs)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_googledrivebackup/__init__.py", line 38, in on_api_command
    from pydrive2.auth import GoogleAuth
ModuleNotFoundError: No module named 'pydrive2'
2022-12-28 00:49:53,364 - octoprint.server.api - ERROR - Error while executing SimpleApiPlugin googledrivebackup
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/server/api/__init__.py", line 158, in pluginCommand
    response = api_plugin.on_api_command(command, data)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/util/__init__.py", line 1688, in wrapper
    return f(*args, **kwargs)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_googledrivebackup/__init__.py", line 38, in on_api_command
    from pydrive2.auth import GoogleAuth
ModuleNotFoundError: No module named 'pydrive2'
2022-12-28 00:49:57,894 - octoprint.server.api - ERROR - Error while executing SimpleApiPlugin googledrivebackup
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/server/api/__init__.py", line 158, in pluginCommand
    response = api_plugin.on_api_command(command, data)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/util/__init__.py", line 1688, in wrapper
    return f(*args, **kwargs)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_googledrivebackup/__init__.py", line 38, in on_api_command
    from pydrive2.auth import GoogleAuth
ModuleNotFoundError: No module named 'pydrive2'
2022-12-28 00:50:12,941 - octoprint.server.api - ERROR - Error while executing SimpleApiPlugin googledrivebackup
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/server/api/__init__.py", line 158, in pluginCommand
    response = api_plugin.on_api_command(command, data)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/util/__init__.py", line 1688, in wrapper
    return f(*args, **kwargs)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_googledrivebackup/__init__.py", line 38, in on_api_command
    from pydrive2.auth import GoogleAuth
ModuleNotFoundError: No module named 'pydrive2'
'

I uninstalled and reinstalled the plugin and I still have the same behavior.  Checked the logs again and the error is still there. 
 Thoughts?

**Comment by jneilliii** [comment]
Yeah, you'll need to do this via SSH to the pi to resolve the problem.

```
sudo apt update
sudo apt upgrade
sudo apt remove rustc
curl https://sh.rustup.rs -sSf | sh
/home/pi/oprint/bin/pip install pydrive2
```

**Comment by Nolemgib** [comment]
Same issue.   Below is excerpt from my logfile, and then see below that for two issue I encountered trying the SSH commands above via Putty.

 File "/home/nolemgib/oprint/lib/python3.7/site-packages/octoprint_googledrivebackup/__init__.py", line 38, in on_api_command
    from pydrive2.auth import GoogleAuth
ModuleNotFoundError: No module named 'pydrive2'
2022-12-29 10:52:47,452 - octoprint.server.heartbeat - INFO - Server heartbeat <3
2022-12-29 10:54:06,321 - octoprint.access.users - INFO - Cleaning up user session A8BFDFD943044B21A172F47DAC0003BE for user nolemgib
2022-12-29 10:54:06,323 - octoprint.access.users - INFO - Logged out user: nolemgib
2022-12-29 10:54:06,371 - octoprint.server.api - ERROR - Error while executing SimpleApiPlugin googledrivebackup
Traceback (most recent call last):
  File "/home/nolemgib/oprint/lib/python3.7/site-packages/octoprint/server/api/__init__.py", line 158, in pluginCommand
    response = api_plugin.on_api_command(command, data)
  File "/home/nolemgib/oprint/lib/python3.7/site-packages/octoprint/util/__init__.py", line 1688, in wrapper
    return f(*args, **kwargs)
  File "/home/nolemgib/oprint/lib/python3.7/site-packages/octoprint_googledrivebackup/__init__.py", line 38, in on_api_command
    from pydrive2.auth import GoogleAuth
ModuleNotFoundError: No module named 'pydrive2'
2022-12-29 10:54:12,004 - octoprint.server.api - ERROR - Error while executing SimpleApiPlugin googledrivebackup
Traceback (most recent call last):
  File "/home/nolemgib/oprint/lib/python3.7/site-packages/octoprint/server/api/__init__.py", line 158, in pluginCommand
    response = api_plugin.on_api_command(command, data)
  File "/home/nolemgib/oprint/lib/python3.7/site-packages/octoprint/util/__init__.py", line 1688, in wrapper
    return f(*args, **kwargs)
  File "/home/nolemgib/oprint/lib/python3.7/site-packages/octoprint_googledrivebackup/__init__.py", line 38, in on_api_command
    from pydrive2.auth import GoogleAuth
ModuleNotFoundError: No module named 'pydrive2'
2022-12-29 10:54:37,255 - octoprint.server.api - ERROR - Error while executing SimpleApiPlugin googledrivebackup
Traceback (most recent call last):
  File "/home/nolemgib/oprint/lib/python3.7/site-packages/octoprint/server/api/__init__.py", line 158, in pluginCommand
    response = api_plugin.on_api_command(command, data)
  File "/home/nolemgib/oprint/lib/python3.7/site-packages/octoprint/util/__init__.py", line 1688, in wrapper
    return f(*args, **kwargs)
  File "/home/nolemgib/oprint/lib/python3.7/site-packages/octoprint_googledrivebackup/__init__.py", line 38, in on_api_command
    from pydrive2.auth import GoogleAuth
ModuleNotFoundError: No module named 'pydrive2'
2022-12-29 11:07:47,454 - octoprint.server.heartbeat - INFO - Server heartbeat <3



When running the SSH commands you listed, I have the following issues starting with the "sudo apt remove rustc" command:

<< REMOVED A TON OF LINES I DID NOT THINK WERE APPLICABLE >>
Get:210 http://archive.raspberrypi.org/debian buster/main armhf rpi-update all 2                                                  0210618 [7,920 B]
Fetched 195 MB in 3min 7s (1,043 kB/s)
Reading changelogs... Done
Extracting templates from packages: 100%
Preconfiguring packages ...
dpkg: unrecoverable fatal error, aborting:
 files list file for package 'libxinerama1:armhf' is missing final newline
E: Sub-process /usr/bin/dpkg returned an error code (2)
nolemgib@octopi:~ $ sudo apt remove rustc
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package 'rustc' is not installed, so not removed
0 upgraded, 0 newly installed, 0 to remove and 210 not upgraded.
nolemgib@octopi:~ $ curl https://sh.rustup.rs -sSf | sh
info: downloading installer

Welcome to Rust!

This will download and install the official compiler for the Rust
programming language, and its package manager, Cargo.

Rustup metadata and toolchains will be installed into the Rustup
home directory, located at:

  /home/nolemgib/.rustup

This can be modified with the RUSTUP_HOME environment variable.

The Cargo home directory is located at:

  /home/nolemgib/.cargo

This can be modified with the CARGO_HOME environment variable.

The cargo, rustc, rustup and other commands will be added to
Cargo's bin directory, located at:

  /home/nolemgib/.cargo/bin

This path will then be added to your PATH environment variable by
modifying the profile files located at:

  /home/nolemgib/.profile
  /home/nolemgib/.bashrc

You can uninstall at any time with rustup self uninstall and
these changes will be reverted.

Current installation options:


   default host triple: armv7-unknown-linux-gnueabihf
     default toolchain: stable (default)
               profile: default
  modify PATH variable: yes

1) Proceed with installation (default)
2) Customize installation
3) Cancel installation
>1

info: profile set to 'default'
info: default host triple is armv7-unknown-linux-gnueabihf
info: syncing channel updates for 'stable-armv7-unknown-linux-gnueabihf'
info: latest update on 2022-12-15, rust version 1.66.0 (69f9c33d7 2022-12-12)
info: downloading component 'cargo'
  6.1 MiB /   6.1 MiB (100 %)   3.9 MiB/s in  2s ETA:  0s
info: downloading component 'clippy'
info: downloading component 'rust-docs'
 19.0 MiB /  19.0 MiB (100 %)   3.2 MiB/s in 59s ETA:  0s
info: downloading component 'rust-std'
 26.9 MiB /  26.9 MiB (100 %)   3.3 MiB/s in 21s ETA:  0s
info: downloading component 'rustc'
 79.4 MiB /  80.4 MiB ( 99 %)   4.4 MiB/s in 19s ETA:  0s^C
nolemgib@octopi:~ $ /home/pi/oprint/bin/pip install pydrive2
-bash: /home/pi/oprint/bin/pip: No such file or directory

**Comment by jneilliii** [comment]
just noticed your username is not the default `pi` user so the command would probably be 

```
/home/nolemgib/oprint/bin/pip install pydrive2
```

**Comment by dwvaughn** [comment]
I got mine working.  I had to update pip and a couple other packages but once I did that, I was able to get it.  Thanks for the help
