### ISSUE TITLE
Surface errors during backup upload

### ISSUE THREAD

**Issue by AndrewADev** [jneilliii/OctoPrint-GoogleDriveBackup#48]
Recently while running/debugging the plugin, I noticed a situation where a failure to refresh a token with invalid credentials (expired or revoked since successful upload - possibly the [auto-expiration for apps in "testing" mentioned here](https://github.com/jneilliii/OctoPrint-GoogleDriveBackup/issues/26#issuecomment-986260646)?) is 'unhandled', and the failure can go unnoticed, unless the user is scanning the logs (or otherwise checking them/the targeted backup location).

As such, I was wondering if it would be possible to somehow surface these and similar errors via the UI? (that backup upload(s) not succeeding)

Snippet from log (from `octoprint serve` output):

```
2023-01-11 10:29:19,093 - octoprint.plugins.softwareupdate - INFO - Saved version cache to disk
  File "****\OctoPrint\venv\lib\site-packages\oauth2client\client.py", line 819, in _do_refresh_request
    raise HttpAccessTokenRefreshError(error_msg, status=resp.status)
oauth2client.client.HttpAccessTokenRefreshError: invalid_grant: Token has been expired or revoked.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "****\octoprint\src\octoprint\plugin\__init__.py", line 273, in call_plugin
    result = getattr(plugin, method)(*args, **kwargs)
  File "****\octoprint\src\octoprint\util\__init__.py", line 1687, in wrapper
    return f(*args, **kwargs)
  File "****\octoprint-googledrivebackup\octoprint_googledrivebackup\__init__.py", line 96, in on_event
    gauth.Refresh()
  File "****\OctoPrint\venv\lib\site-packages\pydrive2\auth.py", line 667, in Refresh
    raise RefreshError("Access token refresh failed: %s" % error)
pydrive2.auth.RefreshError: Access token refresh failed: invalid_grant: Token has been expired or revoked.
```

**Comment by jneilliii** [comment]
Yeah, I've been meaning to add additional error tracking for these situations just haven't had the time to get to it yet. You are correct though, the secrets expire fairly quickly if you remain in test mode.

**Comment by jneilliii** [comment]
closing this as I opened #47 to address already
